### ISSUE TITLE
Check whether CIs are being calculated correctly

### ISSUE THREAD

**Issue by nickreich** [FluSightNetwork/cdc-flusight-ensemble#90] opened 2018-01-05 04:29 UTC
Region 7, for EW51 forecasts, the 50% CI seems far too wide:
![image](https://user-images.githubusercontent.com/1280767/34595557-fb21f0de-f1a6-11e7-9b2c-71b6c5b4ec78.png)

![image](https://user-images.githubusercontent.com/1280767/34595553-f3313722-f1a6-11e7-8e0f-8e1e76737dcc.png)

**Comment by lepisma** [comment] 2018-01-06 06:48
Its `52, 6` (as seen in plots) when we use the following approach (which we are, in the visualizer):
Start from both the right and left side and move towards center while accumulating probability values (via summing) unless we reach 0.25 (which is 0.5 * 50 / 100) independently for both sides.

This is different than _starting from a peak_. The problem is that the if distribution is bimodal (say), starting from a peak (and going down to both sides while accumulating probabilities) might be misleading and might skip the second peak. Do you have suggestions for how to show the multimodal cases?

**Comment by nickreich** [comment] 2018-01-08 15:36
I understand that procedure, but I still don't quite see how the distribution for peak week accumulates .25 probability by EW moving from the right. I get something like 23% by EW6.

**Comment by nickreich** [comment] 2018-01-08 15:40
I guess that's closer than I thought it was, but still seems a bit off to me.

**Comment by lepisma** [comment] 2018-01-13 07:07
I dug into the issue. The values are getting passed correctly to d3-foresight. I am opening an issue on foresight for this https://github.com/reichlab/d3-foresight/issues/37.

**Comment by lepisma** [comment] 2018-02-05 02:27
Found the issue. There was one bin missing when regenerating the whole time series (from week 20xx30 to 20yy29) from the chunk that we have data for (20xx40 to 20yy20). This missing bin was the first bin and so the whole distribution was shifted to left by one.

If, by counting from right, we add another bin (4-5), then we get values >= 0.25. Fixed now.

**Closed** 2018-02-05 18:16 UTC
Labels: visualizer
