### ISSUE TITLE
in 2013/2014, there is no "observed data" until EW52

### ISSUE THREAD

**Issue by nickreich** [FluSightNetwork/cdc-flusight-ensemble#10] opened 2017-08-10 01:23 UTC

**Comment by nickreich** [comment] 2017-08-10 01:25
Is this just because the "unrevised" data is not available before this time?

**Comment by lepisma** [comment] 2017-08-10 11:12
The issue is with how foresight handles observed data. When on week `xx`, showing observed data for all the weeks before (and including) week `xx` asks for data *issued* at week `xx` for all the week before it (like `xx-1`). This is not an issue when we have weekly update of all the past week data in the season (which happens with newer seasons). The problem is with cases like the following:

You are currently at week 4 and you are observing data for week 1, 2 and 4 issued at week 4 (this means that we have lag-3 data for week 1, lag-2 data for week 2 and lag-0 data for week 4). But the most recent data for week 3 is only the one issued at week 3, i.e. lag-0 data.

The *theoretical* observed data (which is what foresight tries to draws) expects the following:
1. lag-3 data for week 1
2. lag-2 data for week 2
3. lag-1 data for week 3
4. lag-0 data for week 4

The *real* observed data (which is what the model creators really observed, if they are using the same data source) doesn't have lag-1 data for week 3 but only lag-0 data.

A fix for this would mean not to look out precisely for `lag-X` data, but to look for any lag value below or equal to `X`.

I will try to fix this, but am not sure this is the only problem making the lines go.

**Closed** 2017-11-05 02:24 UTC
